### ISSUE TITLE
Create the suggestions architecture

### ISSUE THREAD

**Issue by microstudi** [openpoke/decidim-module-participatory-documents#28]
A suggestion is a "comment" created in a section (formerly zones).

- [x] Make suggestion relationship polymorphic. A suggestion can be:
  - [x] Added to the whole document
  - [x] Added to a section only
- [x] List suggestions in the admin side with the following properties:
  - [x] the author of the suggestion.
  - [x] The suggestion truncated (first X characters)
  - [x] the title of the section (see #27). If the suggestion is global, print "Global" (see #33)
  - [x] the state of the comment (similar as proposals, a suggestion can be answered or not). Setting up the state will be done in #32
  - [x] Date of publication
  - [x] Actions: to answer the comment (#32 ).
  Mockup:
  ![imatge](https://user-images.githubusercontent.com/40388743/207902658-46c5f108-1375-45b2-ba8b-59bf706449ac.png)
  - [x] Paginate the results
  - [x] Add seeds to the development app
  - [x] Tests

**Comment by alecslupu** [comment]
Discussed with @paarals and @microstudi to close it, as the redirect is implemented
